<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6668315c1ce9b',
	'title' => 'Infos Album',
	'fields' => array(
		array(
			'key' => 'field_666831aa4cb75',
			'label' => 'Date de sortie',
			'name' => 'date_de_sortie',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'j F Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_666832094cb76',
			'label' => 'Durée de l\'album',
			'name' => 'duree_de_lalbum',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Le champ présent ici ne prend en compte qu\'une unique valeur exprimé en minutes.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'min' => 0,
			'max' => 1000,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6668337abd207',
			'label' => 'Survol Rapide',
			'name' => 'survol_rapide',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Survol Rapide',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_666833febd208',
			'label' => 'Texte du survol rapide',
			'name' => 'texte_du_survol_rapide',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Ici mettez votre texte concernant votre survol rapide',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_66683417bd209',
			'label' => 'Style musical',
			'name' => 'style_musical',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Style musical',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6668342bbd20a',
			'label' => 'Texte style musical',
			'name' => 'texte_style_musical',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Ici mettez le texte concernant le style musical',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_66683443bd20b',
			'label' => 'Impact et héritage',
			'name' => 'impact_et_heritage',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Impact et héritage',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66683452bd20c',
			'label' => 'Texte Impact et héritage',
			'name' => 'texte_impact_et_heritage',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Ici mettez le texte concernant l\'impact et l\'héritage',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_66683a79d8e24',
			'label' => 'titres',
			'name' => 'titres',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'titre',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_66683f6e93d45',
			'label' => 'Artiste principal',
			'name' => 'artiste_principal',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'artiste',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_66683fa693d46',
			'label' => 'Artiste secondaire',
			'name' => 'artiste_secondaire',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'artiste',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6669411c21b60',
			'label' => 'Favori',
			'name' => 'favori',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Favori',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_66694c176d938',
			'label' => 'Jaquette de l\'album',
			'name' => 'jaquette_de_lalbum',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'album',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66683d5f16497',
	'title' => 'Infos Artiste',
	'fields' => array(
		array(
			'key' => 'field_66683d817812f',
			'label' => 'Début d\'activité',
			'name' => 'debut_dactivite',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'j F Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_66683dde78131',
			'label' => 'Nombre de membres',
			'name' => 'nombre_de_membres',
			'aria-label' => '',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'min' => 1,
			'max' => 50,
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66683dfa78132',
			'label' => 'Biographie',
			'name' => 'biographie',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Ils vécurent heureux et eurent beaucoup d\'enfants.',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6669418eb8402',
			'label' => 'Follow',
			'name' => 'follow',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Follow',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_666950edf6c29',
			'label' => 'Photo de l\'artiste',
			'name' => 'photo_de_lartiste',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_666e02de77719',
			'label' => 'Album de l\'artiste',
			'name' => 'album_de_lartiste',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'album',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'artiste',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66683521ad9fc',
	'title' => 'Infos Titre',
	'fields' => array(
		array(
			'key' => 'field_6668400c29795',
			'label' => 'Artiste principal',
			'name' => 'artiste_principal',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'artiste',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6668402829796',
			'label' => 'Artiste secondaire',
			'name' => 'artiste_secondaire',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'artiste',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_66684965361c7',
			'label' => 'Single',
			'name' => 'single',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'La chanson fut-elle un single pour l\'album ?',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'titre',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'genre', array(
	0 => '',
), array(
	'labels' => array(
		'name' => 'Genres',
		'singular_name' => 'Genre',
		'menu_name' => 'Genre',
		'all_items' => 'All Genre',
		'edit_item' => 'Edit Genre',
		'view_item' => 'View Genre',
		'update_item' => 'Update Genre',
		'add_new_item' => 'Add New Genre',
		'new_item_name' => 'New Genre Name',
		'search_items' => 'Search Genre',
		'popular_items' => 'Popular Genre',
		'separate_items_with_commas' => 'Separate genre with commas',
		'add_or_remove_items' => 'Add or remove genre',
		'choose_from_most_used' => 'Choose from the most used genre',
		'not_found' => 'No genre found',
		'no_terms' => 'No genre',
		'items_list_navigation' => 'Genre list navigation',
		'items_list' => 'Genre list',
		'back_to_items' => '← Go to genre',
		'item_link' => 'Genre Link',
		'item_link_description' => 'A link to a genre',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );

	register_taxonomy( 'label', array(
	0 => '',
), array(
	'labels' => array(
		'name' => 'Labels',
		'singular_name' => 'Label',
		'menu_name' => 'Labels',
		'all_items' => 'All Labels',
		'edit_item' => 'Edit Label',
		'view_item' => 'View Label',
		'update_item' => 'Update Label',
		'add_new_item' => 'Add New Label',
		'new_item_name' => 'New Label Name',
		'search_items' => 'Search Labels',
		'popular_items' => 'Popular Labels',
		'separate_items_with_commas' => 'Separate labels with commas',
		'add_or_remove_items' => 'Add or remove labels',
		'choose_from_most_used' => 'Choose from the most used labels',
		'not_found' => 'No labels found',
		'no_terms' => 'No labels',
		'items_list_navigation' => 'Labels list navigation',
		'items_list' => 'Labels list',
		'back_to_items' => '← Go to labels',
		'item_link' => 'Label Link',
		'item_link_description' => 'A link to a label',
	),
	'description' => 'Sous quel label a été distribué l\'album',
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );

	register_taxonomy( 'teinte', array(
	0 => '',
), array(
	'labels' => array(
		'name' => 'Teintes',
		'singular_name' => 'Teinte',
		'menu_name' => 'Teintes',
		'all_items' => 'All Teintes',
		'edit_item' => 'Edit Teinte',
		'view_item' => 'View Teinte',
		'update_item' => 'Update Teinte',
		'add_new_item' => 'Add New Teinte',
		'new_item_name' => 'New Teinte Name',
		'search_items' => 'Search Teintes',
		'popular_items' => 'Popular Teintes',
		'separate_items_with_commas' => 'Separate teintes with commas',
		'add_or_remove_items' => 'Add or remove teintes',
		'choose_from_most_used' => 'Choose from the most used teintes',
		'not_found' => 'No teintes found',
		'no_terms' => 'No teintes',
		'items_list_navigation' => 'Teintes list navigation',
		'items_list' => 'Teintes list',
		'back_to_items' => '← Go to teintes',
		'item_link' => 'Teinte Link',
		'item_link_description' => 'A link to a teinte',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'album', array(
	'labels' => array(
		'name' => 'Albums',
		'singular_name' => 'Album',
		'menu_name' => 'Albums',
		'all_items' => 'All Albums',
		'edit_item' => 'Edit Album',
		'view_item' => 'View Album',
		'view_items' => 'View Albums',
		'add_new_item' => 'Add New Album',
		'add_new' => 'Add New Album',
		'new_item' => 'New Album',
		'parent_item_colon' => 'Parent Album:',
		'search_items' => 'Search Albums',
		'not_found' => 'No albums found',
		'not_found_in_trash' => 'No albums found in Trash',
		'archives' => 'Album Archives',
		'attributes' => 'Album Attributes',
		'insert_into_item' => 'Insert into album',
		'uploaded_to_this_item' => 'Uploaded to this album',
		'filter_items_list' => 'Filter albums list',
		'filter_by_date' => 'Filter albums by date',
		'items_list_navigation' => 'Albums list navigation',
		'items_list' => 'Albums list',
		'item_published' => 'Album published.',
		'item_published_privately' => 'Album published privately.',
		'item_reverted_to_draft' => 'Album reverted to draft.',
		'item_scheduled' => 'Album scheduled.',
		'item_updated' => 'Album updated.',
		'item_link' => 'Album Link',
		'item_link_description' => 'A link to a album.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'genre',
		1 => 'teinte',
		2 => 'label',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'artiste', array(
	'labels' => array(
		'name' => 'Artistes',
		'singular_name' => 'Artiste',
		'menu_name' => 'Artistes',
		'all_items' => 'All Artistes',
		'edit_item' => 'Edit Artiste',
		'view_item' => 'View Artiste',
		'view_items' => 'View Artistes',
		'add_new_item' => 'Add New Artiste',
		'add_new' => 'Add New Artiste',
		'new_item' => 'New Artiste',
		'parent_item_colon' => 'Parent Artiste:',
		'search_items' => 'Search Artistes',
		'not_found' => 'No artistes found',
		'not_found_in_trash' => 'No artistes found in Trash',
		'archives' => 'Artiste Archives',
		'attributes' => 'Artiste Attributes',
		'insert_into_item' => 'Insert into artiste',
		'uploaded_to_this_item' => 'Uploaded to this artiste',
		'filter_items_list' => 'Filter artistes list',
		'filter_by_date' => 'Filter artistes by date',
		'items_list_navigation' => 'Artistes list navigation',
		'items_list' => 'Artistes list',
		'item_published' => 'Artiste published.',
		'item_published_privately' => 'Artiste published privately.',
		'item_reverted_to_draft' => 'Artiste reverted to draft.',
		'item_scheduled' => 'Artiste scheduled.',
		'item_updated' => 'Artiste updated.',
		'item_link' => 'Artiste Link',
		'item_link_description' => 'A link to a artiste.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'titre', array(
	'labels' => array(
		'name' => 'Titres',
		'singular_name' => 'Titre',
		'menu_name' => 'Titres',
		'all_items' => 'All Titres',
		'edit_item' => 'Edit Titre',
		'view_item' => 'View Titre',
		'view_items' => 'View Titres',
		'add_new_item' => 'Add New Titre',
		'add_new' => 'Add New Titre',
		'new_item' => 'New Titre',
		'parent_item_colon' => 'Parent Titre:',
		'search_items' => 'Search Titres',
		'not_found' => 'No titres found',
		'not_found_in_trash' => 'No titres found in Trash',
		'archives' => 'Titre Archives',
		'attributes' => 'Titre Attributes',
		'insert_into_item' => 'Insert into titre',
		'uploaded_to_this_item' => 'Uploaded to this titre',
		'filter_items_list' => 'Filter titres list',
		'filter_by_date' => 'Filter titres by date',
		'items_list_navigation' => 'Titres list navigation',
		'items_list' => 'Titres list',
		'item_published' => 'Titre published.',
		'item_published_privately' => 'Titre published privately.',
		'item_reverted_to_draft' => 'Titre reverted to draft.',
		'item_scheduled' => 'Titre scheduled.',
		'item_updated' => 'Titre updated.',
		'item_link' => 'Titre Link',
		'item_link_description' => 'A link to a titre.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );
} );